import { nodeResolve } from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import terser from '@rollup/plugin-terser';
import replace from '@rollup/plugin-replace';

export default {
  input: 'scripts/canvas.bundle.entry.js',
  output: {
    file: 'src/zen/vendor/canvas.bundle.js',
    format: 'iife',
    name: 'ZenCanvas',
    sourcemap: false,
  },
  plugins: [
    replace({
      preventAssignment: true,
      // Define process as a global object
      'typeof process === "undefined"': 'false',
      'process.env.NODE_ENV': '"production"',
      'process.env': '{}',
      'process.browser': 'true',
      'process.version': '"v16.0.0"',
      'process.platform': '"browser"',
      'process.nextTick': 'setTimeout',
      'process.cwd': '() => ""',
      'process.chdir': '() => {}',
      'process.umask': '() => 0',
      'process.uptime': '() => 0',
      'process.hrtime': '() => [0, 0]',
      'process.memoryUsage': '() => ({ heapUsed: 0, heapTotal: 0, external: 0, rss: 0 })',
      'process.exit': '() => {}',
      'process.kill': '() => {}',
      'process.on': '() => {}',
      'process.off': '() => {}',
      'process.emit': '() => {}',
      'process.listeners': '() => []',
      'process.removeAllListeners': '() => {}',
      'process.removeListener': '() => {}',
      'process.addListener': '() => {}',
      'process.prependListener': '() => {}',
      'process.prependOnceListener': '() => {}',
      'process.once': '() => {}',
      'process.setMaxListeners': '() => {}',
      'process.getMaxListeners': '() => 0',
      'process.listenerCount': '() => 0',
      'process.eventNames': '() => []',
      'process.rawListeners': '() => []',
      'process.setUncaughtExceptionCaptureCallback': '() => {}',
      'process.hasUncaughtExceptionCaptureCallback': '() => false',
      'process.setUnhandledRejectionCaptureCallback': '() => {}',
      'process.hasUnhandledRejectionCaptureCallback': '() => false',
      'process.emitWarning': '() => {}',
      'process.binding': '() => {}',
      'process.moduleLoadList': '[]',
      'process.release': '{}',
      'process.features': '{}',
      'process.versions': '{}',
      'process.arch': '"x64"',
      'process.pid': '0',
      'process.title': '"browser"',
      'process.argv': '[]',
      'process.execArgv': '[]',
      'process.execPath': '""',
      'process.mainModule': 'undefined',
      'process.connected': 'false',
      'process.allowedNodeEnvironmentFlags': '[]',
      'process.debugPort': '0',
      'process.noDeprecation': 'false',
      'process.throwDeprecation': 'false',
      'process.traceDeprecation': 'false',
      'process.dlopen': '() => {}',
      'process.hrtime.bigint': '() => BigInt(0)',
      'process.cpuUsage': '() => ({ user: 0, system: 0 })',
      'process.resourceUsage': '() => ({ fsRead: 0, fsWrite: 0, voluntaryContextSwitches: 0, involuntaryContextSwitches: 0 })',
      // Add global process definition
      'global.process': 'window.process',
      'global.process.env': 'window.process.env',
      // More aggressive replacements
      'typeof process !== "undefined"': 'true',
      'process && process.env': 'window.process && window.process.env',
      'process.env.NODE_ENV || "development"': '"production"',
    }),
    nodeResolve({ 
      browser: true, 
      preferBuiltins: false,
    }),
    commonjs({
      transformMixedEsModules: true,
    }),
    terser({
      compress: {
        drop_console: false,
      },
    }),
  ],
};
